name: Database change CD

on:
  push:
    branches:
    - main
      
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  migrate_db:
    name: Migrate DB
    runs-on: self-hosted
    steps:
      - name: Clone the repo
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          aws-region: "eu-west-1"

      - name: Perform migration
        uses: liquibase-github-actions/update@v4.26.0
        with:
          changelogFile: "./database/liquibase/changelog.yaml"
          url: ${{ secrets.FLYWAY_DB_URL}}
          password: "${{secrets.FLYWAY_PASSWORD}}"
          username: "${{secrets.FLYWAY_USER}}"
