name: "Database CI/CD"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  Migrate:
    name: RunMigration
    runs-on: self-hosted  
    steps:
    - run: |
       docker run --rm \
       -v /database/flyway/sql:/flyway/sql \
       flyway/flyway \
       -url=${{ secrets.FLYWAY_DB_URL }} \
       -user=${{ secrets.FLYWAY_USER }} \
       -password=${{ secrets.FLYWAY_PASSWORD}} \
       migrate
