name: "Database CI/CD"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  Migrate:
    name: RunMigration
    runs-on: self-hosted  
    steps:
    - uses: docker://flyway/flyway:9
      env:
        FLYWAY_URL: ${{ secrets.FLYWAY_DB_URL }}
        FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
        FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD}}
        FLYWAY_LOCATIONS: ./database/flyway/sql
