name: "Database CI/CD"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  Migrate:
    name: RunMigration
    runs-on: self-hosted         
    steps:
      - name: RunMigration
        uses: actions/checkout@v3.0.0
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.FLYWAY_DB_URL }}
          user: ${{ secrets.FLYWAY_USER }}
          password: ${{ secrets.FLYWAY_PASSWORD }}
