name: "Database CI/CD"
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  Migrate:
    name: RunMigration
    runs-on: self-hosted         
    steps:
      - name: RunMigration
        uses: actions/checkout@v3.0.0
      - run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin
      - run: flyway -user="${{ secrets.FLYWAY_USER }}" -password="${{ secrets.FLYWAY_PASSWORD }}" -url="${{ secrets.FLYWAY_DB_URL }}" -baselineOnMigrate="true" -locations="/database/flyway/sql" migrate
